require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'

target 'qrcode' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
    )
    
    permissions_path = '../node_modules/react-native-permissions/ios'


    pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
      'BarcodeDetectorMLKit'
    ]

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    target 'qrcodeTests' do
      inherit! :complete
      # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  
  post_install do |installer|
    react_native_post_install(installer)
    # Only for Mac M1 if needed
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    
    # set a specific port for Mtro bundler
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] + ['RCT_METRO_PORT=8089']
          end
        end
      end
    end
  end


end